Adapt script to also work on macOS
chpatton013/ssh-agent-canonicalize pull request #2
Opened 2021-10-04 21:46 UTC by rfagen-zoox

New laptop, who dis?

2022-03-01 21:02 UTC, chpatton013 requested changes

2022-03-01 21:02 UTC, chpatton013 commented on ssh-agent-canonicalize
> +if [[ $OSTYPE == 'darwin'* ]]; then
The BSD options should work fine for the GNU versions of these commands. Let's just simplify it to use the short-opts. Then we don't need any variables or anything; we can just update the use of the args below.

2022-03-01 21:02 UTC, chpatton013 commented on ssh-agent-canonicalize
> +  echo $( pgrep ssh-agent | grep -v "^$(canon_agent_pid)$" )
I don't remember the history of why I made this function so complicated, but we can actually go one step further and remove the echo:
```
pgrep ssh-agent | grep -v "^$(canon_agent_pid)$"
```

2022-04-01 16:12 UTC, rfagen-zoox commented
Ok. Finally found a moment. Cleaned up, tested on both 14.04 (lol) and macOS bash/zsh

2022-04-01 16:32 UTC, rfagen-zoox commented
Otherwise, I believe the function `non_canon_agent_pids` won't actually return anything and causes the script to bail due to the `set -euo pipefail` ?

2022-04-01 16:46 UTC, chpatton013 approved these changes

2022-04-01 16:47 UTC, merged